
import { Question } from './types';

export const STATIC_QUESTIONS: Question[] = [
  { id: '1', text: "What is Angular Framework?", category: "Basics" },
  { id: '2', text: "What is the difference between AngularJS and Angular?", category: "Basics" },
  { id: '3', text: "What is TypeScript?", category: "Basics" },
  { id: '4', text: "Write a pictorial diagram of Angular architecture?", category: "Basics" },
  { id: '5', text: "What are the key components of Angular?", category: "Architecture" },
  { id: '6', text: "What are directives?", category: "Basics" },
  { id: '7', text: "What are components?", category: "Basics" },
  { id: '8', text: "What are the differences between Component and Directive?", category: "Basics" },
  { id: '9', text: "What is a template?", category: "Basics" },
  { id: '10', text: "What is a module?", category: "Basics" },
  { id: '11', text: "What are the lifecycle hooks available?", category: "Lifecycle" },
  { id: '12', text: "What is data binding?", category: "Basics" },
  { id: '13', text: "What is metadata?", category: "Architecture" },
  { id: '14', text: "What is Angular CLI?", category: "Tooling" },
  { id: '15', text: "What is the difference between constructor and ngOnInit?", category: "Lifecycle" },
  { id: '16', text: "What is a service?", category: "Architecture" },
  { id: '17', text: "What is dependency injection in Angular?", category: "Architecture" },
  { id: '18', text: "How is Dependency Hierarchy formed?", category: "Architecture" },
  { id: '19', text: "What is the purpose of async pipe?", category: "Pipes" },
  { id: '20', text: "What is the option to choose between inline and external template file?", category: "Basics" },
  { id: '21', text: "What is the purpose of *ngFor directive?", category: "Directives" },
  { id: '22', text: "What is the purpose of ngIf directive?", category: "Directives" },
  { id: '23', text: "What happens if you use script tag inside template?", category: "Security" },
  { id: '24', text: "What is interpolation?", category: "Data Binding" },
  { id: '25', text: "What are template expressions?", category: "Data Binding" },
  { id: '26', text: "What are template statements?", category: "Data Binding" },
  { id: '27', text: "How do you categorize data binding types?", category: "Data Binding" },
  { id: '28', text: "What are pipes?", category: "Pipes" },
  { id: '29', text: "What is a parameterized pipe?", category: "Pipes" },
  { id: '30', text: "How do you chain pipes?", category: "Pipes" },
  { id: '31', text: "What is a custom pipe?", category: "Pipes" },
  { id: '35', text: "What are observables?", category: "RxJS" },
  { id: '36', text: "What is HttpClient and its benefits?", category: "HTTP" },
  { id: '40', text: "What is RxJS?", category: "RxJS" },
  { id: '44', text: "What is the difference between promise and observable?", category: "RxJS" },
  { id: '63', text: "What is Angular Router?", category: "Routing" },
  { id: '75', text: "What is Angular Universal?", category: "Advanced" },
  { id: '111', text: "What is Angular Ivy?", category: "Advanced" },
  { id: '143', text: "What is lazy loading?", category: "Advanced" },
  { id: '158', text: "What is schematic?", category: "Tooling" },
  { id: '162', text: "What is Angular security model for preventing XSS attacks?", category: "Security" },
  { id: '256', text: "What are reactive forms?", category: "Forms" },
  { id: '258', text: "What are template driven forms?", category: "Forms" },
  // ... Simplified for space but would include all requested entries in a real app
];
